Code to add variables for the regression modelling to the final dataset

In [1]:
import pandas as pd

In [2]:
# start from final_df dataset
hosp_df_final = pd.read_csv('./data/final_df.csv')

In [3]:
hosp_df_final.head()

,state,date,critical_staffing_shortage_today_yes,critical_staffing_shortage_today_no,critical_staffing_shortage_today_not_reported,critical_staffing_shortage_anticipated_within_week_yes,critical_staffing_shortage_anticipated_within_week_no,critical_staffing_shortage_anticipated_within_week_not_reported,hospital_onset_covid,hospital_onset_covid_coverage,...,percent_of_inpatients_with_covid_coverage,inpatient_bed_covid_utilization,inpatient_bed_covid_utilization_coverage,adult_icu_bed_covid_utilization,adult_icu_bed_covid_utilization_coverage,adult_icu_bed_utilization,adult_icu_bed_utilization_coverage,deaths_covid,deaths_covid_coverage,isBurden
0,AK,2020-03-23,0,0,1,0,0,1,0.0,1,...,1.0,0.053571,1.0,0.0,0.0,0.0,0.0,0.0,1,0
1,AK,2020-03-24,0,0,1,0,0,1,0.0,1,...,1.0,0.053571,1.0,0.0,0.0,0.0,0.0,0.0,1,0
2,AK,2020-03-25,0,0,1,0,0,1,0.0,1,...,1.0,0.017857,1.0,0.0,0.0,0.0,0.0,0.0,1,0
3,AK,2020-03-26,0,0,1,0,0,1,0.0,1,...,1.0,0.035714,1.0,0.0,0.0,0.0,0.0,0.0,1,0
4,AK,2020-03-27,0,0,2,0,0,2,0.0,2,...,2.0,0.012346,2.0,0.0,0.0,0.0,0.0,0.0,2,0

In [23]:
hosp_df_final.shape

(35541, 36)

In [4]:
# add social deprivation index SDI
# Data Source: Appendix A table in https://www.census.gov/content/dam/Census/library/working-papers/2020/demo/SEHSD-WP2020-08.pdf

deprivation_data = pd.read_csv('./data/deprivation_indices_2018.csv')
deprivation_data.head()

,State,Original,Original s.e.,Adjusted,Adjusted s.e.,ADI,ADI s.e.,State ADI,State ADI s.e.,SDI,SDI s.e.,State SDI,State SDI s.e.,Mobility,Mobility s.e.
0,United States,15.02,0.05,15.52,0.05,14.92,0.05,15.00,0.05,15.68,0.05,15.54,0.05,14.90,0.05
1,Alabama,21.74,0.29,19.97,0.28,17.96,0.27,16.84,0.27,17.01,0.28,17.54,0.27,16.46,0.27
2,Alaska,11.40,0.63,15.00,0.64,11.66,0.63,13.60,0.67,12.29,0.64,13.94,0.66,11.02,0.63
3,Arizona,13.81,0.23,14.82,0.24,16.50,0.24,15.87,0.24,18.15,0.25,16.59,0.25,17.64,0.24
4,Arkansas,17.48,0.39,18.65,0.40,17.81,0.41,16.46,0.41,16.78,0.39,17.26,0.39,16.01,0.39

In [5]:
# drop US row 
deprivation_data = deprivation_data.iloc[1: , :]

In [6]:
# map state name to state abbrv
# dictionary credit: https://gist.github.com/rogerallen/1583593
us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "U.S. Virgin Islands": "VI",
}

deprivation_data['state'] = deprivation_data.State.map(us_state_to_abbrev)

In [7]:
deprivation_data = deprivation_data[['state', 'SDI']]

In [8]:
#merge
final_regression_df = pd.merge(hosp_df_final, deprivation_data, how="left", on='state')

In [9]:
# add population density 
# Data Source:  Population Density Data - https://www.census.gov/data/tables/time-series/dec/density-data-text.html

pop_density = pd.read_csv('./data/us_popn_density_2020_census.csv')
pop_density.head()

         Area  Resident Population  Population Density
0     Alabama              5024279                   99
1      Alaska               733391                    1
2     Arizona              7151502                   63
3    Arkansas              3011524                   58
4  California             39538223                  254

In [10]:
pop_density['state'] = pop_density.Area.map(us_state_to_abbrev)
pop_density.head()
pop_density.columns

Index(['Area', 'Resident Population', 'Population Density ', 'state'], dtype='object')

In [11]:
pop_density = pop_density[['state', 'Population Density ']]

In [12]:
#merge
final_regression_df = pd.merge(final_regression_df, pop_density, how="left", on='state')

In [13]:
final_regression_df.head()

,state,date,critical_staffing_shortage_today_yes,critical_staffing_shortage_today_no,critical_staffing_shortage_today_not_reported,critical_staffing_shortage_anticipated_within_week_yes,critical_staffing_shortage_anticipated_within_week_no,critical_staffing_shortage_anticipated_within_week_not_reported,hospital_onset_covid,hospital_onset_covid_coverage,...,inpatient_bed_covid_utilization_coverage,adult_icu_bed_covid_utilization,adult_icu_bed_covid_utilization_coverage,adult_icu_bed_utilization,adult_icu_bed_utilization_coverage,deaths_covid,deaths_covid_coverage,isBurden,SDI,Population Density
0,AK,2020-03-23,0,0,1,0,0,1,0.0,1,...,1.0,0.0,0.0,0.0,0.0,0.0,1,0,12.29,1
1,AK,2020-03-24,0,0,1,0,0,1,0.0,1,...,1.0,0.0,0.0,0.0,0.0,0.0,1,0,12.29,1
2,AK,2020-03-25,0,0,1,0,0,1,0.0,1,...,1.0,0.0,0.0,0.0,0.0,0.0,1,0,12.29,1
3,AK,2020-03-26,0,0,1,0,0,1,0.0,1,...,1.0,0.0,0.0,0.0,0.0,0.0,1,0,12.29,1
4,AK,2020-03-27,0,0,2,0,0,2,0.0,2,...,2.0,0.0,0.0,0.0,0.0,0.0,2,0,12.29,1

In [15]:
# add number of hospitals per state
# Data Source: https://www.kff.org/other/state-indicator/total-hospitals/

# csv file with hospital counts by state 
hosp_numbers = pd.read_csv('./data/hospitals_by_state.csv')
hosp_numbers.head(5)

        Location  Total Hospitals
0  United States             5141
1        Alabama              101
2         Alaska               20
3        Arizona               80
4       Arkansas               89

In [16]:
#drop row for US
hosp_numbers = hosp_numbers[1:]

In [18]:
hosp_numbers['state'] = hosp_numbers.Location.map(us_state_to_abbrev)

In [19]:
hosp_numbers = hosp_numbers[['state', 'Total Hospitals']]
# rename
hosp_numbers = hosp_numbers.rename({'Total Hospitals': 'total_hospitals'}, axis=1)

In [20]:
#merge
final_regression_df = pd.merge(final_regression_df, hosp_numbers, how="left", on='state')

In [21]:
final_regression_df.head()

,state,date,critical_staffing_shortage_today_yes,critical_staffing_shortage_today_no,critical_staffing_shortage_today_not_reported,critical_staffing_shortage_anticipated_within_week_yes,critical_staffing_shortage_anticipated_within_week_no,critical_staffing_shortage_anticipated_within_week_not_reported,hospital_onset_covid,hospital_onset_covid_coverage,...,adult_icu_bed_covid_utilization,adult_icu_bed_covid_utilization_coverage,adult_icu_bed_utilization,adult_icu_bed_utilization_coverage,deaths_covid,deaths_covid_coverage,isBurden,SDI,Population Density,total_hospitals
0,AK,2020-03-23,0,0,1,0,0,1,0.0,1,...,0.0,0.0,0.0,0.0,0.0,1,0,12.29,1,20
1,AK,2020-03-24,0,0,1,0,0,1,0.0,1,...,0.0,0.0,0.0,0.0,0.0,1,0,12.29,1,20
2,AK,2020-03-25,0,0,1,0,0,1,0.0,1,...,0.0,0.0,0.0,0.0,0.0,1,0,12.29,1,20
3,AK,2020-03-26,0,0,1,0,0,1,0.0,1,...,0.0,0.0,0.0,0.0,0.0,1,0,12.29,1,20
4,AK,2020-03-27,0,0,2,0,0,2,0.0,2,...,0.0,0.0,0.0,0.0,0.0,2,0,12.29,1,20

In [22]:
final_regression_df.shape

(35541, 39)

In [24]:
final_regression_df.to_csv('final_regression_df.csv', index=False)

In [26]:
# sanity check
pd.read_csv('final_regression_df.csv').head()
pd.read_csv('final_regression_df.csv').shape

(35541, 39)